### ISSUE TITLE
Getting Error -> fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths

### ISSUE THREAD

**Issue by carl-alberto** [rtCamp/action-phpcs-code-review#19]
Tried to create a PR in my site but it seems the `commit ID` is not getting the empty values, here is the error logs:

```
COMMIT ID: 
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
 _________________________________________

Running the following command
/home/rtbot/vip-go-ci-tools/vip-go-ci/vip-go-ci.php --repo-owner=owner --repo-name=Plugin-Repo-Name --commit= --token=$GH_BOT_TOKEN --phpcs-path=/home/rtbot/vip-go-ci-tools/phpcs/bin/phpcs --local-git-repo=/home/rtbot/github-workspace --phpcs=true --phpcs-standard=WordPress,WordPress-Core,WordPress-Docs --lint=true
[ 2019-12-26T07:46:48+05:30 -- 0 ]  Initializing...; {
    "debug_info": {
        "php_version": "7.2.24-0ubuntu0.18.04.1",
        "hostname": "62d9c6a543d7",
        "php_uname": "Linux 62d9c6a543d7 5.0.0-1027-azure #29~18.04.1-Ubuntu SMP Mon Nov 25 21:18:57 UTC 2019 x86_64"
    }
}
```

**Comment by mrrobot47** [comment]
@carl-alberto thanks for reporting the issue. This has occurred due to changes in the checkout actions in the newer `v2` version which has breaking changes in working functionality.

I have updated the code and made branch `v2.0.0` as the default branch for this repo. Please update your action run according to the updates in the [usage](https://github.com/rtCamp/action-phpcs-code-review#usage).

Key changes that you need to make that have updated in the readme are:

1. `actions/checkout` should be tagged to `@v2` and have the given `ref`:
```
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
```
2. `rtcamp/action-phpcs-code-review` should be tagged to `@v2.0.0`
```
    - uses: rtcamp/action-phpcs-code-review@v2.0.0
```
**or** you can use the docker image for a faster action run (read the side note at the end in [usage](https://github.com/rtCamp/action-phpcs-code-review#usage)):
```
    - uses: docker://rtcamp/action-phpcs-code-review:v2.0.0
```

**Comment by mrrobot47** [comment]
Closing this as it has been fixed in: https://github.com/rtCamp/action-phpcs-code-review/commit/bf44cd0013d51be50ffb75030469d536967d2807

Please check these changes and feel free to re-open the issue in case you face any other errors in this update.

**Comment by carl-alberto** [comment]
Thanks @mrrobot47! it is now working!
