### ISSUE TITLE
Error: Filenames should be all lowercase with hyphens as word separators.

### ISSUE THREAD

**Issue by w3bdesign** [rtCamp/action-phpcs-code-review#34]
Getting the following error:

```
 Error: Filenames should be all lowercase with hyphens as word separators. Expected phpcs-scan-omtoxh.php, but found phpcs-scan-omTOXH.php (WordPress.Files.FileName.NotHyphenatedLowercase).
```

My filename is inde-xer.php

Is this a bug or am I misunderstanding something here?

**Comment by mrrobot47** [comment]
That is a known issue, it is happening because [vip-go-ci](https://github.com/automattic/vip-go-ci), the core part of this action takes the diff. of PR and puts it in a temp file. That temp file name causes this issue.

This bug will be fixed soon. Till then, please add your phpcs rulsets in `phpcs.xml` file in the root of your repository. That `phpcs.xml` will be taken into consideration while running phpcs. You can use [this phpcs.xml](https://github.com/rtCamp/wordpress-skeleton/blob/master/phpcs.xml) as a base which ignores the `NotHyphenatedLowercase` error and add other rulesets you want for your project in it.

**Comment by w3bdesign** [comment]
That fixed the issue, thanks.

**Comment by dannydover** [comment]
Any ETA on when this will be fixed? I see the workaround, but would prefer to keep that rule in place as it is useful.

Alternatively, is there a way to ignore all filenames that match _phpcs-scan-_*

Thank you.
